# Analysis
FED_SPLIT_ANCESTRY=1
FED_CHR=chr22
FED_NSUB=5000
FED_NGENES=20
FED_NPCS=5
FED_CKKS=PN14QP438
FED_DATABITS=60
FED_FRACBITS=30
FED_PHENO_COL=LDLC_final_mgdl_6sd_masked
FED_PROBES=50
FED_CSV=1

# Inputs
GENO_GCS=gs://vwb-aou-datasets-controlled/v9/wgs/short_read/snpindel/exome/pgen/exome.${FED_CHR}
COV_GCS=gs://vwb-aou-datasets-controlled/v9/wgs/short_read/snpindel/aux/ancestry/ancestry_preds.tsv
PHENO_GCS=gs://gwas-data-wgs-wb-jaunty-blueberry-8679/pheno/v9_final_lipid_med_corrected_short_read_tot.csv

# Batch
BATCH_ROOT=gs://dataproc-staging-${GOOGLE_CLOUD_PROJECT}/secure-skat
BATCH_REGION=us-west1
BATCH_IMAGE=gcr.io/${GOOGLE_CLOUD_PROJECT}/secure-skat-runner:latest
BATCH_TIMEOUT=24h
BATCH_MIN_CORES=16
BATCH_MIN_RAM=64
BATCH_BOOT_DISK_SIZE=50
BATCH_DISK_SIZE=500
