run_dir = "${HOME}/secure-rvas-aou"
chromosomes = [21, 22]

genotype = "gs://vwb-aou-datasets-controlled/v9/wgs/short_read/snpindel/exome/pgen/exome.{chromosome}"
annotation = "${HOME}/fed_prep_out/{chromosome}_annotation.tsv"
phenotype = "gs://gwas-data-wgs-wb-jaunty-blueberry-8679/pheno/v9_final_lipid_med_corrected_short_read_tot.csv"
covariate = "gs://vwb-aou-datasets-controlled/v9/wgs/short_read/snpindel/aux/ancestry/ancestry_preds.tsv"
ancestry = "gs://vwb-aou-datasets-controlled/v9/wgs/short_read/snpindel/aux/ancestry/ancestry_preds.tsv"
genes = "${HOME}/secure_skat_smoke_genes.txt"

phenotype_id_column = "person_id"
covariate_id_column = "research_id"
covariate_column = "pca_features"
ancestry_id_column = "research_id"
ancestry_column = "ancestry_pred_other"
ancestries = ["EUR", "AFR", "AMR"]
num_cov = 16
phenotype_columns = [
  "LDLC_final_mgdl_6sd_masked",
  "HDLC_mgdl_6sd_masked",
  "TotChol_corrected_mvp_explicit_duration_mgdl_6sd_masked",
  "ln_Trig_6sd_masked",
  "nonHDL_corrected_mvp_explicit_duration_mgdl_6sd_masked",
]
masks = ["annotation=pLoF"]
samples_per_cohort = 0
sample_seed = 42
role_seed = 42

ckks = "PN14QP436S45"
mpc_num_threads = 2
data_bits = 70
fractional_bits = 30
probes = 50
seed = 42
binding_ipaddr = "127.0.0.1"

plink2_bin = "${HOME}/plink2"

[servers.party0]
ipaddr = "127.0.0.1"
ports = {party1 = "18000", party2 = "18002"}

[servers.party1]
ipaddr = "127.0.0.1"
ports = {party2 = "18004"}

[servers.party2]
ipaddr = "127.0.0.1"
ports = {}