run_dir = "/home/dataproc/secure-rvas-aou"
shared_keys_path = "/home/dataproc/secure-rvas-aou/secure/keys/Party1"
local_num_threads = 8

genotype_dir = "/home/dataproc/secure-rvas-aou/prepared/{ancestry}/chr{chromosome}/A/geno"
phenotype_file = "/home/dataproc/secure-rvas-aou/prepared/{ancestry}/chr{chromosome}/A/pheno.txt"
covariate_file = "/home/dataproc/secure-rvas-aou/prepared/{ancestry}/chr{chromosome}/A/cov.txt"
genes_file = "/home/dataproc/secure-rvas-aou/prepared/{ancestry}/chr{chromosome}/genes.txt"
variant_counts_file = "/home/dataproc/secure-rvas-aou/prepared/{ancestry}/chr{chromosome}/block_sizes.txt"
