run_dir = "output/cp0"

chromosomes = [22]
phenotype_columns = ["LDLC_final_mgdl_6sd_masked", "HDLC_mgdl_6sd_masked"]
ancestries = ["EUR"]
num_cov = 10

ckks = "PN14QP436S45"
mpc_num_threads = 2
data_bits = 70
fractional_bits = 40
probes = 50
seed = 42

binding_ipaddr = "127.0.0.1"

[servers.party0]
ipaddr = "127.0.0.1"
ports = {party1 = "18000", party2 = "18002"}

[servers.party1]
ipaddr = "127.0.0.1"
ports = {party2 = "18004"}

[servers.party2]
ipaddr = "127.0.0.1"
ports = {}
