genotype = "rewrite/testdata/1kgenome/generated/genotype/chr{chromosome}"
gene_panel = "rewrite/testdata/1kgenome/generated/gene_panel/chr{chromosome}.tsv"
annotation = "rewrite/testdata/1kgenome/generated/annotation/chr{chromosome}.tsv"
phenotype = "rewrite/testdata/1kgenome/generated/phenotype.csv"
covariate = "rewrite/testdata/1kgenome/generated/ancestry_pred.tsv"
ancestry = "rewrite/testdata/1kgenome/generated/ancestry_pred.tsv"

phenotype_id_column = "IID"
covariate_id_column = "research_id"
covariate_column = "pca_features"
ancestry_id_column = "research_id"
ancestry_column = "ancestry_pred_other"
masks = ["LoF=HC"]
max_maf = 0.01
samples_per_cohort = 0
sample_seed = 42
role_seed = 42
plink2_bin = "plink2"

[gene_selection]
mode = "all"
